name: deliveryapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-178.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  google_sign_in: ^5.1.1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/category/
    - assets/images/items/
    - assets/images/offers/
